const QUERY_DISEASES = "countries.QUERY_DISEASES";
const QUERY_DISEASES_SUCCEDED = "countries.QUERY_DISEASES_SUCCEDED";
const QUERY_DISEASES_FAILED = "countries.QUERY_DISEASES_FAILED";

const REQUEST_DISEASE_FETCH = "countries.REQUEST_DISEASE_FETCH";
const DISEASE_FETCH_SUCCEDED = "countries.DISEASE_FETCH_SUCCEDED";
const DISEASE_FETCH_FAILED = "countries.DISEASE_FETCH_FAILED";

const REQUEST_ADD_DISEASE = "countries.REQUEST_ADD_DISEASE";
const ADD_DISEASE_SUCCEDED = "countries.ADD_DISEASE_SUCCEDED";
const ADD_DISEASE_FAILED = "countries.ADD_DISEASE_FAILED";

const REQUEST_DELETE_DISEASE = "countries.REQUEST_DELETE_DISEASE";
const DELETE_DISEASE_SUCCEDED = "countries.DELETE_DISEASE_SUCCEDED";
const DELETE_DISEASE_FAILED = "countries.DELETE_DISEASE_FAILED";



const DISEASE_CLEAR_MATCHES = "countries.DISEASE_CLEAR_MATCHES";

export {
	QUERY_DISEASES,
	QUERY_DISEASES_SUCCEDED,
	QUERY_DISEASES_FAILED,
	REQUEST_ADD_DISEASE,
	ADD_DISEASE_SUCCEDED,
	ADD_DISEASE_FAILED,
	REQUEST_DELETE_DISEASE,
	DELETE_DISEASE_SUCCEDED,
	DELETE_DISEASE_FAILED,
	DISEASE_CLEAR_MATCHES,

	REQUEST_DISEASE_FETCH,
	DISEASE_FETCH_SUCCEDED,
	DISEASE_FETCH_FAILED
}