version: '3'
services:
  web:
    image: node
    environment:
      - SUPER_ADMIN_USER=karthik1729
      - SUPER_ADMIN_PASSWORD=karthik001
      - FRONTEND_HOST=http://localhost:3001
    depends_on:
      - db
    volumes:
      - "./backend:/tmp"
    working_dir: /tmp
    entrypoint: npm start
    ports:
      - 3000:3000
  frontend:
    image: node
    depends_on:
      - web
    volumes:
      - "./frontend-client:/tmp"
    working_dir: /tmp
    entrypoint: npm start
    ports:
     - 3001:3000
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - "~/data/db:/data/db"
