const QUERY_PET_TYPES = "countries.QUERY_PET_TYPES";
const QUERY_PET_TYPES_SUCCEEDED = "countries.QUERY_PET_TYPES_SUCCEEDED";
const QUERY_PET_TYPES_FAILED = "countries.QUERY_PET_TYPES_FAILED";

const QUERY_BREEDS = "countries.QUERY_BREEDS";
const QUERY_BREEDS_SUCCEEDED = "countries.QUERY_BREEDS_SUCCEEDED";
const QUERY_BREEDS_FAILED = "countries.QUERY_BREEDS_FAILED";

const REQUEST_ADD_PET_TYPE = "countries.REQUEST_ADD_PET_TYPE";
const ADD_PET_TYPE_SUCCEEDED = "countries.ADD_PET_TYPE_SUCCEEDED";
const ADD_PET_TYPE_FAILED = "countries.ADD_PET_TYPE_FAILED";

const REQUEST_PET_TYPE_FETCH = "petTypes.REQUEST_PET_TYPE_FETCH"
const PET_TYPE_FETCH_SUCCEEDED = "petTypes.PET_TYPE_FETCH_SUCCEEDED"
const PET_TYPE_FETCH_FAILED = "petTypes.PET_TYPE_FETCH_FAILED"


const REQUEST_UPDATE_PET_TYPE = "countries.REQUEST_UPDATE_PET_TYPE";
const UPDATE_PET_TYPE_SUCCEEDED = "countries.UPDATE_PET_TYPE_SUCCEEDED";
const UPDATE_PET_TYPE_FAILED = "countries.UPDATE_PET_TYPE_FAILED";

const REQUEST_ADD_BREED = "countries.REQUEST_ADD_BREED";
const ADD_BREED_SUCCEEDED = "countries.ADD_BREED_SUCCEEDED";
const ADD_BREED_FAILED = "countries.ADD_BREED_FAILED";

const REQUEST_DELETE_PET_TYPE = "countries.REQUEST_DELETE_PET_TYPE";
const DELETE_PET_TYPE_SUCCEEDED = "countries.DELETE_PET_TYPE_SUCCEEDED";
const DELETE_PET_TYPE_FAILED = "countries.DELETE_PET_TYPE_FAILED";

const PET_TYPE_CLEAR_MATCHES = "countries.PET_TYPE_CLEAR_MATCHES";
const BREED_CLEAR_MATCHES = "countries.BREED_CLEAR_MATCHES";

const REQUEST_ADD_VISIT = "petTypes.REQUEST_ADD_VISIT"
const ADD_VISIT_SUCCEEDED = "petTypes.ADD_VISIT_SUCCEEDED"
const ADD_VISIT_FAILED = "petTypes.ADD_VISIT_FAILED"

export {
	QUERY_PET_TYPES,
	QUERY_PET_TYPES_SUCCEEDED,
	QUERY_PET_TYPES_FAILED,
	QUERY_BREEDS,
	QUERY_BREEDS_SUCCEEDED,
	QUERY_BREEDS_FAILED,
	REQUEST_ADD_PET_TYPE,
	ADD_PET_TYPE_SUCCEEDED,
	ADD_PET_TYPE_FAILED,
	REQUEST_DELETE_PET_TYPE,
	DELETE_PET_TYPE_SUCCEEDED,
	DELETE_PET_TYPE_FAILED,
	PET_TYPE_CLEAR_MATCHES,
	REQUEST_ADD_BREED,
	ADD_BREED_SUCCEEDED,
	ADD_BREED_FAILED,
	BREED_CLEAR_MATCHES,
	REQUEST_UPDATE_PET_TYPE,
	UPDATE_PET_TYPE_SUCCEEDED,
	UPDATE_PET_TYPE_FAILED,

	REQUEST_PET_TYPE_FETCH,
	PET_TYPE_FETCH_SUCCEEDED,
	PET_TYPE_FETCH_FAILED,

	REQUEST_ADD_VISIT,
	ADD_VISIT_SUCCEEDED,
	ADD_VISIT_FAILED
}