const QUERY_VET_CENTERS = "vetCenters.QUERY_VET_CENTERS";
const FETCHED_VET_CENTERS = "vetCenters.FETCHED_VET_CENTERS";
const FAILED_FETCH_VET_CENTERS = "vetCenters.FAILED_FETCH_VET_CENTERS";

export {
	QUERY_VET_CENTERS,
	FETCHED_VET_CENTERS,
	FAILED_FETCH_VET_CENTERS
}