const QUERY_VET_CENTERS = "vetCenters.QUERY_VET_CENTERS";
const QUERY_VET_CENTERS_SUCCEDED = "vetCenters.QUERY_VET_CENTERS_SUCCEDED";
const QUERY_VET_CENTERS_FAILED = "vetCenters.QUERY_VET_CENTERS_FAILED";

const CLEAR_VET_CENTER = "vetCenters.CLEAR_VET_CENTER";

const REQUEST_VET_CENTER_FETCH = "vetCenters.REQUEST_VET_CENTER_FETCH";
const VET_CENTER_FETCH_SUCCEDED = "vetCenters.VET_CENTER_FETCH_SUCCEDED";
const VET_CENTER_FETCH_FAILED = "vetCenters.VET_CENTER_FETCH_FAILED";

const REQUEST_ADD_VET_CENTER = "vetCenters.REQUEST_ADD_VET_CENTER";
const ADD_VET_CENTER_SUCCEDED = "vetCenters.ADD_VET_CENTER_SUCCEDED";
const ADD_VET_CENTER_FAILED = "vetCenters.ADD_VET_CENTER_FAILED";

const REQUEST_DELETE_VET_CENTER = "vetCenters.REQUEST_DELETE_VET_CENTER";
const DELETE_VET_CENTER_SUCCEDED = "vetCenters.DELETE_VET_CENTER_SUCCEDED";
const DELETE_VET_CENTER_FAILED = "vetCenters.DELETE_VET_CENTER_FAILED";

const REQUEST_ADMINS_FETCH = "vetCenters.REQUEST_ADMINS_FETCH";
const ADMINS_FETCH_SUCCEDED = "vetCenters.ADMINS_FETCH_SUCCEDED";
const ADMINS_FETCH_FAILED = "vetCenters.ADMINS_FETCH_FAILED";

const REQUEST_ADD_ADMIN = "vetCenters.REQUEST_ADD_ADMIN";
const ADD_ADMIN_SUCCEDED = "vetCenters.ADD_ADMIN_SUCCEDED";
const ADD_ADMIN_FAILED = "vetCenters.ADD_ADMIN_FAILED";

const REQUEST_DELETE_ADMIN = "vetCenters.REQUEST_DELETE_ADMIN";
const DELETE_ADMIN_SUCCEDED = "vetCenters.DELETE_ADMIN_SUCCEDED";
const DELETE_ADMIN_FAILED = "vetCenters.DELETE_ADMIN_FAILED";



const VET_CENTER_CLEAR_MATCHES = "vetCenters.VET_CENTER_CLEAR_MATCHES";

export {
	QUERY_VET_CENTERS,
	QUERY_VET_CENTERS_SUCCEDED,
	QUERY_VET_CENTERS_FAILED,
	REQUEST_ADD_VET_CENTER,
	ADD_VET_CENTER_SUCCEDED,
	ADD_VET_CENTER_FAILED,
	REQUEST_DELETE_VET_CENTER,
	DELETE_VET_CENTER_SUCCEDED,
	DELETE_VET_CENTER_FAILED,
	VET_CENTER_CLEAR_MATCHES,
	CLEAR_VET_CENTER,
	REQUEST_VET_CENTER_FETCH,
	VET_CENTER_FETCH_SUCCEDED,
	VET_CENTER_FETCH_FAILED,
	REQUEST_ADD_ADMIN,
	ADD_ADMIN_SUCCEDED,
	ADD_ADMIN_FAILED,
	REQUEST_ADMINS_FETCH,
	ADMINS_FETCH_SUCCEDED,
	ADMINS_FETCH_FAILED,
	REQUEST_DELETE_ADMIN,
	DELETE_ADMIN_SUCCEDED,
	DELETE_ADMIN_FAILED
}