const QUERY_VET_CENTERS = "countries.QUERY_VET_CENTERS";
const QUERY_VET_CENTERS_SUCCEDED = "countries.QUERY_VET_CENTERS_SUCCEDED";
const QUERY_VET_CENTERS_FAILED = "countries.QUERY_VET_CENTERS_FAILED";

const REQUEST_VET_CENTER_FETCH = "countries.REQUEST_VET_CENTER_FETCH";
const VET_CENTER_FETCH_SUCCEDED = "countries.VET_CENTER_FETCH_SUCCEDED";
const VET_CENTER_FETCH_FAILED = "countries.VET_CENTER_FETCH_FAILED";

const REQUEST_ADD_VET_CENTER = "countries.REQUEST_ADD_VET_CENTER";
const ADD_VET_CENTER_SUCCEDED = "countries.ADD_VET_CENTER_SUCCEDED";
const ADD_VET_CENTER_FAILED = "countries.ADD_VET_CENTER_FAILED";

const REQUEST_DELETE_VET_CENTER = "countries.REQUEST_DELETE_VET_CENTER";
const DELETE_VET_CENTER_SUCCEDED = "countries.DELETE_VET_CENTER_SUCCEDED";
const DELETE_VET_CENTER_FAILED = "countries.DELETE_VET_CENTER_FAILED";



const VET_CENTER_CLEAR_MATCHES = "countries.VET_CENTER_CLEAR_MATCHES";

export {
	QUERY_VET_CENTERS,
	QUERY_VET_CENTERS_SUCCEDED,
	QUERY_VET_CENTERS_FAILED,
	REQUEST_ADD_VET_CENTER,
	ADD_VET_CENTER_SUCCEDED,
	ADD_VET_CENTER_FAILED,
	REQUEST_DELETE_VET_CENTER,
	DELETE_VET_CENTER_SUCCEDED,
	DELETE_VET_CENTER_FAILED,
	VET_CENTER_CLEAR_MATCHES,

	REQUEST_VET_CENTER_FETCH,
	VET_CENTER_FETCH_SUCCEDED,
	VET_CENTER_FETCH_FAILED
}