const QUERY_VACCINATIONS = "vaccinations.QUERY_VACCINATIONS";
const QUERY_VACCINATIONS_SUCCEDED = "vaccinations.QUERY_VACCINATIONS_SUCCEDED";
const QUERY_VACCINATIONS_FAILED = "vaccinations.QUERY_VACCINATIONS_FAILED";

export {
	QUERY_VACCINATIONS,
	QUERY_VACCINATIONS_SUCCEDED,
	QUERY_VACCINATIONS_FAILED
}