const QUERY_VACCINATIONS = "vaccinations.QUERY_VACCINATIONS";
const QUERY_VACCINATIONS_SUCCEEDED = "vaccinations.QUERY_VACCINATIONS_SUCCEEDED";
const QUERY_VACCINATIONS_FAILED = "vaccinations.QUERY_VACCINATIONS_FAILED";

export {
	QUERY_VACCINATIONS,
	QUERY_VACCINATIONS_SUCCEEDED,
	QUERY_VACCINATIONS_FAILED
}