const QUERY_VISITS = "visits.QUERY_VISITS";
const QUERY_VISITS_SUCCEDED = "visits.QUERY_VISITS_SUCCEDED";
const QUERY_VISITS_FAILED = "visits.QUERY_VISITS_FAILED";
const CLEAR_VISIT = "visits.CLEAR_VISIT";

export {
	QUERY_VISITS,
	QUERY_VISITS_SUCCEDED,
	QUERY_VISITS_FAILED,
	CLEAR_VISIT
}