const QUERY_VISITS = "visits.QUERY_VISITS";
const QUERY_VISITS_SUCCEDED = "visits.QUERY_VISITS_SUCCEDED";
const QUERY_VISITS_FAILED = "visits.QUERY_VISITS_FAILED";
const REQUEST_ADD_BIOMETRIC = "visits.REQUEST_ADD_BIOMETRIC";
const ADD_BIOMETRIC_SUCCEDED = "visits.ADD_BIOMETRIC_SUCCEDED";
const ADD_BIOMETRIC_FAILED = "visits.ADD_BIOMETRIC_FAILED";
const CLEAR_VISIT = "visits.CLEAR_VISIT";

export {
	QUERY_VISITS,
	QUERY_VISITS_SUCCEDED,
	QUERY_VISITS_FAILED,
	CLEAR_VISIT,
	REQUEST_ADD_BIOMETRIC,
	ADD_BIOMETRIC_SUCCEDED,
	ADD_BIOMETRIC_FAILED
}