const QUERY_VISITS = "visits.QUERY_VISITS";
const QUERY_VISITS_SUCCEEDED = "visits.QUERY_VISITS_SUCCEEDED";
const QUERY_VISITS_FAILED = "visits.QUERY_VISITS_FAILED";
const REQUEST_ADD_BIOMETRIC = "visits.REQUEST_ADD_BIOMETRIC";
const ADD_BIOMETRIC_SUCCEEDED = "visits.ADD_BIOMETRIC_SUCCEEDED";
const ADD_BIOMETRIC_FAILED = "visits.ADD_BIOMETRIC_FAILED";
const CLEAR_VISIT = "visits.CLEAR_VISIT";

export {
	QUERY_VISITS,
	QUERY_VISITS_SUCCEEDED,
	QUERY_VISITS_FAILED,
	CLEAR_VISIT,
	REQUEST_ADD_BIOMETRIC,
	ADD_BIOMETRIC_SUCCEEDED,
	ADD_BIOMETRIC_FAILED
}