const REQUEST_ADD_REQUEST = "countries.REQUEST_ADD_REQUEST";
const ADD_REQUEST_SUCCEDED = "countries.ADD_REQUEST_SUCCEDED";
const ADD_REQUEST_FAILED = "countries.ADD_REQUEST_FAILED";


export {
	REQUEST_ADD_REQUEST,
	ADD_REQUEST_SUCCEDED,
	ADD_REQUEST_FAILED
}