const QUERY_COUNTRIES = "countries.QUERY_COUNTRIES";
const FETCHED_COUNTRIES = "countries.FETCHED_COUNTRIES";
const FAILED_FETCH_COUNTRIES = "countries.FAILED_FETCH_COUNTRIES";

const QUERY_STATES = "countries.QUERY_STATES";
const FETCHED_STATES = "countries.FETCHED_STATES";
const FAILED_FETCH_STATES = "countries.FAILED_FETCH_STATES";


const REQUEST_ADD_COUNTRY = "countries.REQUEST_ADD_COUNTRY";
const REQUEST_ADD_STATE = "countries.REQUEST_ADD_STATE";
const REQUEST_DELETE_COUNTRY = "countries.REQUEST_DELETE_COUNTRY";
const ADD_COUNTRY_SUCCEDED = "countries.ADD_COUNTRY_SUCCEDED";
const ADD_COUNTRY_FAILED = "countries.ADD_COUNTRY_FAILED";
const DELETE_COUNTRY_SUCCEDED = "countries.DELETE_COUNTRY_SUCCEDED";
const DELETE_COUNTRY_FAILED = "countries.DELETE_COUNTRY_FAILED";
const COUNTRY_CLEAR_MATCHES = "countries.COUNTRY_CLEAR_MATCHES";

export {
	QUERY_COUNTRIES,
	FETCHED_COUNTRIES,
	FAILED_FETCH_COUNTRIES,
	QUERY_STATES,
	FETCHED_STATES,
	FAILED_FETCH_STATES,
	REQUEST_ADD_COUNTRY,
	ADD_COUNTRY_SUCCEDED,
	ADD_COUNTRY_FAILED,
	REQUEST_DELETE_COUNTRY,
	DELETE_COUNTRY_SUCCEDED,
	DELETE_COUNTRY_FAILED,
	COUNTRY_CLEAR_MATCHES,
	REQUEST_ADD_STATE
}