const QUERY_COUNTRIES = "countries.QUERY_COUNTRIES";
const QUERY_COUNTRIES_SUCCEDED = "countries.QUERY_COUNTRIES_SUCCEDED";
const QUERY_COUNTRIES_FAILED = "countries.QUERY_COUNTRIES_FAILED";

const QUERY_STATES = "countries.QUERY_STATES";
const QUERY_STATES_SUCCEDED = "countries.QUERY_STATES_SUCCEDED";
const QUERY_STATES_FAILED = "countries.QUERY_STATES_FAILED";

const REQUEST_ADD_COUNTRY = "countries.REQUEST_ADD_COUNTRY";
const ADD_COUNTRY_SUCCEDED = "countries.ADD_COUNTRY_SUCCEDED";
const ADD_COUNTRY_FAILED = "countries.ADD_COUNTRY_FAILED";

const REQUEST_ADD_STATE = "countries.REQUEST_ADD_STATE";
const ADD_STATE_SUCCEDED = "countries.ADD_STATE_SUCCEDED";
const ADD_STATE_FAILED = "countries.ADD_STATE_FAILED";

const REQUEST_DELETE_COUNTRY = "countries.REQUEST_DELETE_COUNTRY";
const DELETE_COUNTRY_SUCCEDED = "countries.DELETE_COUNTRY_SUCCEDED";
const DELETE_COUNTRY_FAILED = "countries.DELETE_COUNTRY_FAILED";

const COUNTRY_CLEAR_MATCHES = "countries.COUNTRY_CLEAR_MATCHES";
const STATE_CLEAR_MATCHES = "countries.STATE_CLEAR_MATCHES";

export {
	QUERY_COUNTRIES,
	QUERY_COUNTRIES_SUCCEDED,
	QUERY_COUNTRIES_FAILED,
	QUERY_STATES,
	QUERY_STATES_SUCCEDED,
	QUERY_STATES_FAILED,
	REQUEST_ADD_COUNTRY,
	ADD_COUNTRY_SUCCEDED,
	ADD_COUNTRY_FAILED,
	REQUEST_DELETE_COUNTRY,
	DELETE_COUNTRY_SUCCEDED,
	DELETE_COUNTRY_FAILED,
	COUNTRY_CLEAR_MATCHES,
	REQUEST_ADD_STATE,
	ADD_STATE_SUCCEDED,
	ADD_STATE_FAILED,
	STATE_CLEAR_MATCHES
}