const QUERY_VACCINES = "countries.QUERY_VACCINES";
const QUERY_VACCINES_SUCCEEDED = "countries.QUERY_VACCINES_SUCCEEDED";
const QUERY_VACCINES_FAILED = "countries.QUERY_VACCINES_FAILED";

const REQUEST_VACCINE_FETCH = "countries.REQUEST_VACCINE_FETCH";
const VACCINE_FETCH_SUCCEEDED = "countries.VACCINE_FETCH_SUCCEEDED";
const VACCINE_FETCH_FAILED = "countries.VACCINE_FETCH_FAILED";

const REQUEST_ADD_VACCINE = "countries.REQUEST_ADD_VACCINE";
const ADD_VACCINE_SUCCEEDED = "countries.ADD_VACCINE_SUCCEEDED";
const ADD_VACCINE_FAILED = "countries.ADD_VACCINE_FAILED";

const REQUEST_ADD_DOSAGE = "countries.REQUEST_ADD_DOSAGE";
const ADD_DOSAGE_SUCCEEDED = "countries.ADD_DOSAGE_SUCCEEDED";
const ADD_DOSAGE_FAILED = "countries.ADD_DOSAGE_FAILED";

const REQUEST_DELETE_DOSAGE = "countries.REQUEST_DELETE_DOSAGE";
const DELETE_DOSAGE_SUCCEEDED = "countries.DELETE_DOSAGE_SUCCEEDED";
const DELETE_DOSAGE_FAILED = "countries.DELETE_DOSAGE_FAILED";

const REQUEST_DELETE_VACCINE = "countries.REQUEST_DELETE_VACCINE";
const DELETE_VACCINE_SUCCEEDED = "countries.DELETE_VACCINE_SUCCEEDED";
const DELETE_VACCINE_FAILED = "countries.DELETE_VACCINE_FAILED";

const VACCINE_CLEAR_MATCHES = "countries.VACCINE_CLEAR_MATCHES";
const CLEAR_VACCINES = "countries.CLEAR_VACCINES";

export {
	QUERY_VACCINES,
	QUERY_VACCINES_SUCCEEDED,
	QUERY_VACCINES_FAILED,
	REQUEST_ADD_VACCINE,
	ADD_VACCINE_SUCCEEDED,
	ADD_VACCINE_FAILED,
	REQUEST_DELETE_VACCINE,
	DELETE_VACCINE_SUCCEEDED,
	DELETE_VACCINE_FAILED,
	VACCINE_CLEAR_MATCHES,

	REQUEST_VACCINE_FETCH,
	VACCINE_FETCH_SUCCEEDED,
	VACCINE_FETCH_FAILED,

	REQUEST_ADD_DOSAGE,
	ADD_DOSAGE_SUCCEEDED,
	ADD_DOSAGE_FAILED,

	REQUEST_DELETE_DOSAGE,
	DELETE_DOSAGE_SUCCEEDED,
	DELETE_DOSAGE_FAILED,
	CLEAR_VACCINES
}