const QUERY_VACCINES = "vaccines.QUERY_VACCINES";
const FETCHED_VACCINES = "vaccines.FETCHED_VACCINES";
const FAILED_FETCH_VACCINES = "vaccines.FAILED_FETCH_VACCINES";
const REQUEST_ADD_VACCINE = "vaccines.REQUEST_ADD_VACCINE";
const REQUEST_UPDATE_VACCINE = "vaccines.REQUEST_UPDATE_VACCINE";
const REQUEST_DELETE_VACCINE = "vaccines.REQUEST_DELETE_VACCINE";
const ADD_VACCINE_SUCCEDED = "vaccines.ADD_VACCINE_SUCCEDED";
const ADD_VACCINE_FAILED = "vaccines.ADD_VACCINE_FAILED";

export {
	QUERY_VACCINES,
	FETCHED_VACCINES,
	FAILED_FETCH_VACCINES,
	REQUEST_ADD_VACCINE,
	ADD_VACCINE_SUCCEDED,
	ADD_VACCINE_FAILED,
	REQUEST_UPDATE_VACCINE,
	REQUEST_DELETE_VACCINE
}