const QUERY_VACCINES = "countries.QUERY_VACCINES";
const QUERY_VACCINES_SUCCEDED = "countries.QUERY_VACCINES_SUCCEDED";
const QUERY_VACCINES_FAILED = "countries.QUERY_VACCINES_FAILED";

const REQUEST_VACCINE_FETCH = "countries.REQUEST_VACCINE_FETCH";
const VACCINE_FETCH_SUCCEDED = "countries.VACCINE_FETCH_SUCCEDED";
const VACCINE_FETCH_FAILED = "countries.VACCINE_FETCH_FAILED";

const REQUEST_ADD_VACCINE = "countries.REQUEST_ADD_VACCINE";
const ADD_VACCINE_SUCCEDED = "countries.ADD_VACCINE_SUCCEDED";
const ADD_VACCINE_FAILED = "countries.ADD_VACCINE_FAILED";

const REQUEST_DELETE_VACCINE = "countries.REQUEST_DELETE_VACCINE";
const DELETE_VACCINE_SUCCEDED = "countries.DELETE_VACCINE_SUCCEDED";
const DELETE_VACCINE_FAILED = "countries.DELETE_VACCINE_FAILED";



const VACCINE_CLEAR_MATCHES = "countries.VACCINE_CLEAR_MATCHES";

export {
	QUERY_VACCINES,
	QUERY_VACCINES_SUCCEDED,
	QUERY_VACCINES_FAILED,
	REQUEST_ADD_VACCINE,
	ADD_VACCINE_SUCCEDED,
	ADD_VACCINE_FAILED,
	REQUEST_DELETE_VACCINE,
	DELETE_VACCINE_SUCCEDED,
	DELETE_VACCINE_FAILED,
	VACCINE_CLEAR_MATCHES,

	REQUEST_VACCINE_FETCH,
	VACCINE_FETCH_SUCCEDED,
	VACCINE_FETCH_FAILED
}