const REQUEST_CREATE_USER = "user.REQUEST_CREATE_USER";
const CREATE_USER_SUCCEEDED = "user.CREATE_USER_SUCCEEDED";
const CREATE_USER_FAILED = "user.CREATE_USER_FAILED";
const CLEAR_USER = "user.CLEAR_USER";

export {
	REQUEST_CREATE_USER,
	CREATE_USER_SUCCEEDED,
	CREATE_USER_FAILED,
	CLEAR_USER
}