const REQUEST_CREATE_USER= "user.REQUEST_CREATE_USER";
const CREATE_USER_SUCCEDED= "user.CREATE_USER_SUCCEDED";
const CREATE_USER_FAILED= "user.CREATE_USER_FAILED";

export {
    REQUEST_CREATE_USER,
    CREATE_USER_SUCCEDED,
    CREATE_USER_FAILED
}