const QUERY_DISEASES = "countries.QUERY_DISEASES";
const QUERY_DISEASES_SUCCEEDED = "countries.QUERY_DISEASES_SUCCEEDED";
const QUERY_DISEASES_FAILED = "countries.QUERY_DISEASES_FAILED";

const REQUEST_DISEASE_FETCH = "countries.REQUEST_DISEASE_FETCH";
const DISEASE_FETCH_SUCCEEDED = "countries.DISEASE_FETCH_SUCCEEDED";
const DISEASE_FETCH_FAILED = "countries.DISEASE_FETCH_FAILED";

const REQUEST_ADD_DISEASE = "countries.REQUEST_ADD_DISEASE";
const ADD_DISEASE_SUCCEEDED = "countries.ADD_DISEASE_SUCCEEDED";
const ADD_DISEASE_FAILED = "countries.ADD_DISEASE_FAILED";

const REQUEST_DELETE_DISEASE = "countries.REQUEST_DELETE_DISEASE";
const DELETE_DISEASE_SUCCEEDED = "countries.DELETE_DISEASE_SUCCEEDED";
const DELETE_DISEASE_FAILED = "countries.DELETE_DISEASE_FAILED";


const DISEASE_CLEAR_MATCHES = "countries.DISEASE_CLEAR_MATCHES";

export {
	QUERY_DISEASES,
	QUERY_DISEASES_SUCCEEDED,
	QUERY_DISEASES_FAILED,
	REQUEST_ADD_DISEASE,
	ADD_DISEASE_SUCCEEDED,
	ADD_DISEASE_FAILED,
	REQUEST_DELETE_DISEASE,
	DELETE_DISEASE_SUCCEEDED,
	DELETE_DISEASE_FAILED,
	DISEASE_CLEAR_MATCHES,

	REQUEST_DISEASE_FETCH,
	DISEASE_FETCH_SUCCEEDED,
	DISEASE_FETCH_FAILED
}