const REQUEST_GENERATE_TOKENS   = "tokens.REQUEST_GENERATE_TOKENS";
const GENERATE_TOKENS_SUCCEEDED  = "tokens.GENERATE_TOKENS_SUCCEEDED";
const GENERATE_TOKENS_FAILED    = "tokens.GENERATE_TOKENS_FAILED";

const REQUEST_UPDATE_TOKEN  = "tokens.REQUEST_UPDATE_TOKEN";
const UPDATE_TOKEN_SUCCEEDED = "tokens.UPDATE_TOKEN_SUCCEEDED";
const UPDATE_TOKEN_FAILED   = "tokens.UPDATE_TOKEN_FAILED";

const CLEAR_TOKENS    = "tokens.CLEAR_TOKENS";

export {
	CLEAR_TOKENS,
	REQUEST_GENERATE_TOKENS,
	GENERATE_TOKENS_SUCCEEDED,
	GENERATE_TOKENS_FAILED,
	REQUEST_UPDATE_TOKEN,
	UPDATE_TOKEN_SUCCEEDED,
	UPDATE_TOKEN_FAILED,
}