const REQUEST_GENERATE_TOKENS   = "tokens.REQUEST_GENERATE_TOKENS";
const GENERATE_TOKENS_SUCCEDED  = "tokens.GENERATE_TOKENS_SUCCEDED";
const GENERATE_TOKENS_FAILED    = "tokens.GENERATE_TOKENS_FAILED";

const REQUEST_UPDATE_TOKEN  = "tokens.REQUEST_UPDATE_TOKEN";
const UPDATE_TOKEN_SUCCEDED = "tokens.UPDATE_TOKEN_SUCCEDED";
const UPDATE_TOKEN_FAILED   = "tokens.UPDATE_TOKEN_FAILED";

const CLEAR_TOKENS    = "tokens.CLEAR_TOKENS";

export {
	CLEAR_TOKENS,
	REQUEST_GENERATE_TOKENS,
	GENERATE_TOKENS_SUCCEDED,
	GENERATE_TOKENS_FAILED,
	REQUEST_UPDATE_TOKEN,
	UPDATE_TOKEN_SUCCEDED,
	UPDATE_TOKEN_FAILED,
}