const REQUEST_GENERATE_TOKENS   = "tokens.REQUEST_GENERATE_TOKENS";
const GENERATE_TOKENS_SUCCEDED  = "tokens.GENERATE_TOKENS_SUCCEDED";
const GENERATE_TOKENS_FAILED    = "tokens.GENERATE_TOKENS_FAILED";
const CLEAR_TOKENS    = "tokens.CLEAR_TOKENS";

export {
	CLEAR_TOKENS,
	REQUEST_GENERATE_TOKENS,
	GENERATE_TOKENS_SUCCEDED,
	GENERATE_TOKENS_FAILED
}