const REQUEST_ADD_REQUEST = "countries.REQUEST_ADD_REQUEST";
const ADD_REQUEST_SUCCEEDED = "countries.ADD_REQUEST_SUCCEEDED";
const ADD_REQUEST_FAILED = "countries.ADD_REQUEST_FAILED";


export {
	REQUEST_ADD_REQUEST,
	ADD_REQUEST_SUCCEEDED,
	ADD_REQUEST_FAILED
}