const REQUEST_GUARDIAN_FETCH = "pets.REQUEST_GUARDIAN_FETCH";
const GUARDIAN_FETCH_SUCCEDED = "pets.GUARDIAN_FETCH_SUCCEDED";
const GUARDIAN_FETCH_FAILED = "pets.GUARDIAN_FETCH_FAILED";

const CLEAR_GUARDIAN = "pets.CLEAR_GUARDIAN";

export {
    REQUEST_GUARDIAN_FETCH,
    GUARDIAN_FETCH_SUCCEDED,
    GUARDIAN_FETCH_FAILED,
    CLEAR_GUARDIAN,
}