const REQUEST_GUARDIAN_FETCH = "pets.REQUEST_GUARDIAN_FETCH";
const GUARDIAN_FETCH_SUCCEDED = "pets.GUARDIAN_FETCH_SUCCEDED";
const GUARDIAN_FETCH_FAILED = "pets.GUARDIAN_FETCH_FAILED";

const REQUEST_CREATE_PET = "pets.REQUEST_CREATE_PET";
const CREATE_PET_SUCCEDED = "pets.CREATE_PET_SUCCEDED";
const CREATE_PET_FAILED = "pets.CREATE_PET_FAILED";

const CLEAR_GUARDIAN = "pets.CLEAR_GUARDIAN";

export {
	REQUEST_GUARDIAN_FETCH,
	GUARDIAN_FETCH_SUCCEDED,
	GUARDIAN_FETCH_FAILED,
	CLEAR_GUARDIAN,
	REQUEST_CREATE_PET,
	CREATE_PET_SUCCEDED,
	CREATE_PET_FAILED,
}