const AUTH_CLEAR = "auth.CLEAR";
const REQUEST_LOGIN = "auth.REQUEST_LOGIN";
const LOGIN_SUCCEDED = "auth.LOGIN_SUCCEDED";
const LOGIN_FAILED = "auth.LOGIN_FAILED";
const CHECK_LOGIN = "auth.CHECK_LOGIN";
const LOGIN_CHECK_SUCCEDED = "auth.LOGIN_CHECK_SUCCEDED";
const LOGIN_CHECK_FAILED = "auth.LOGIN_CHECK_FAILED";
const REQUEST_SIGNUP = "auth.REQUEST_SIGNUP";
const SIGNUP_SUCCEDED = "auth.SIGNUP_SUCCEDED";
const SIGNUP_FAILED = "auth.SIGNUP_FAILED";
const REQUEST_ACCOUNT_RESET = "auth.REQUEST_ACCOUNT_RESET";
const ACCOUNT_RESET_SUCCEDED = "auth.ACCOUNT_RESET_SUCCEDED";
const ACCOUNT_RESET_FAILED = "auth.ACCOUNT_RESET_FAILED";
const REQUEST_PASSWORD_RESET = "auth.REQUEST_PASSWORD_RESET";
const PASSWORD_RESET_SUCCEDED = "auth.PASSWORD_RESET_SUCCEDED";
const PASSWORD_RESET_FAILED = "auth.PASSWORD_RESET_FAILED";

export {
	AUTH_CLEAR,
	REQUEST_LOGIN,
	LOGIN_SUCCEDED,
	LOGIN_FAILED,
	CHECK_LOGIN,
	LOGIN_CHECK_SUCCEDED,
	LOGIN_CHECK_FAILED,
	REQUEST_SIGNUP,
	SIGNUP_SUCCEDED,
	SIGNUP_FAILED,
	REQUEST_ACCOUNT_RESET,
	ACCOUNT_RESET_SUCCEDED,
	ACCOUNT_RESET_FAILED,
	REQUEST_PASSWORD_RESET,
	PASSWORD_RESET_SUCCEDED,
	PASSWORD_RESET_FAILED,
}