const AUTH_CLEAR = "auth.CLEAR";

const REQUEST_SUPER_ADMIN_LOGIN = "auth.REQUEST_SUPER_ADMIN_LOGIN";
const SUPER_ADMIN_LOGIN_SUCCEDED = "auth.SUPER_ADMIN_LOGIN_SUCCEDED";
const SUPER_ADMIN_LOGIN_FAILED = "auth.SUPER_ADMIN_LOGIN_FAILED";

const REQUEST_SUPER_ADMIN_LOGOUT = "auth.REQUEST_SUPER_ADMIN_LOGOUT";
const SUPER_ADMIN_LOGOUT_SUCCEDED = "auth.SUPER_ADMIN_LOGOUT_SUCCEDED";
const SUPER_ADMIN_LOGOUT_FAILED = "auth.SUPER_ADMIN_LOGOUT_FAILED";

const REQUEST_LOGOUT = "auth.REQUEST_LOGOUT";
const LOGOUT_SUCCEDED = "auth.LOGOUT_SUCCEDED";
const LOGOUT_FAILED = "auth.LOGOUT_FAILED";


const REQUEST_LOGIN = "auth.REQUEST_LOGIN";
const LOGIN_SUCCEDED = "auth.LOGIN_SUCCEDED";
const LOGIN_FAILED = "auth.LOGIN_FAILED";

const CHECK_SUPER_ADMIN = "auth.CHECK_SUPER_ADMIN";
const CHECK_SUPER_ADMIN_PASSED = "auth.CHECK_SUPER_ADMIN_PASSED";
const CHECK_SUPER_ADMIN_FAILED = "auth.CHECK_SUPER_ADMIN_FAILED";

const CHECK_ADMIN = "auth.CHECK_LOGIN";
const CHECK_ADMIN_PASSED = "auth.CHECK_ADMIN_PASSED";
const CHECK_ADMIN_FAILED = "auth.CHECK_ADMIN_FAILED";

const REQUEST_SIGNUP = "auth.REQUEST_SIGNUP";
const SIGNUP_SUCCEDED = "auth.SIGNUP_SUCCEDED";
const SIGNUP_FAILED = "auth.SIGNUP_FAILED";

const REQUEST_ACCOUNT_RESET = "auth.REQUEST_ACCOUNT_RESET";
const ACCOUNT_RESET_SUCCEDED = "auth.ACCOUNT_RESET_SUCCEDED";
const ACCOUNT_RESET_FAILED = "auth.ACCOUNT_RESET_FAILED";

const REQUEST_PASSWORD_RESET = "auth.REQUEST_PASSWORD_RESET";
const PASSWORD_RESET_SUCCEDED = "auth.PASSWORD_RESET_SUCCEDED";
const PASSWORD_RESET_FAILED = "auth.PASSWORD_RESET_FAILED";

export {
	AUTH_CLEAR,

	REQUEST_SUPER_ADMIN_LOGIN,
	SUPER_ADMIN_LOGIN_SUCCEDED,
	SUPER_ADMIN_LOGIN_FAILED,

	REQUEST_SUPER_ADMIN_LOGOUT,
	SUPER_ADMIN_LOGOUT_SUCCEDED,
	SUPER_ADMIN_LOGOUT_FAILED,


	REQUEST_LOGIN,
	LOGIN_SUCCEDED,
	LOGIN_FAILED,

	CHECK_SUPER_ADMIN,
	CHECK_SUPER_ADMIN_PASSED,
	CHECK_SUPER_ADMIN_FAILED,

	CHECK_ADMIN,
	CHECK_ADMIN_PASSED,
	CHECK_ADMIN_FAILED,

	REQUEST_SIGNUP,
	SIGNUP_SUCCEDED,
	SIGNUP_FAILED,

	REQUEST_ACCOUNT_RESET,
	ACCOUNT_RESET_SUCCEDED,
	ACCOUNT_RESET_FAILED,

	REQUEST_PASSWORD_RESET,
	PASSWORD_RESET_SUCCEDED,
	PASSWORD_RESET_FAILED,

	REQUEST_LOGOUT,
	LOGOUT_SUCCEDED,
	LOGOUT_FAILED,
}